# -*- coding: utf-8 -*-
"""
UI definition for MainWindow
Generated from Qt Designer UI file -- font overrides removed;
font consistency is handled by the application-level stylesheet.
"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1911, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 931, 951))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_acquisition = QtWidgets.QWidget()
        self.tab_acquisition.setObjectName("tab_acquisition")
        self.graph_layout = QtWidgets.QWidget(self.tab_acquisition)
        self.graph_layout.setGeometry(QtCore.QRect(10, 240, 911, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_layout.sizePolicy().hasHeightForWidth())
        self.graph_layout.setSizePolicy(sizePolicy)
        self.graph_layout.setObjectName("graph_layout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.graph_layout)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mplwindow = QtWidgets.QWidget(self.graph_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setObjectName("mplwindow")
        self.mplvl = QtWidgets.QVBoxLayout(self.mplwindow)
        self.mplvl.setObjectName("mplvl")
        self.verticalLayout.addWidget(self.mplwindow)
        self.external_laser_checkbox = QtWidgets.QCheckBox(self.tab_acquisition)
        self.external_laser_checkbox.setGeometry(QtCore.QRect(240, 70, 171, 31))
        self.external_laser_checkbox.setChecked(False)
        self.external_laser_checkbox.setObjectName("external_laser_checkbox")
        self.laser_stop_button = QtWidgets.QPushButton(self.tab_acquisition)
        self.laser_stop_button.setEnabled(False)
        self.laser_stop_button.setObjectName("laser_stop_button")
        self.Connect_laser_button = QtWidgets.QPushButton(self.tab_acquisition)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Connect_laser_button.sizePolicy().hasHeightForWidth())
        self.Connect_laser_button.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Connect_laser_button.setPalette(palette)
        self.Connect_laser_button.setStyleSheet("")
        self.Connect_laser_button.setIconSize(QtCore.QSize(32, 32))
        self.Connect_laser_button.setObjectName("Connect_laser_button")
        self.progressBar_laser = QtWidgets.QProgressBar(self.tab_acquisition)
        self.progressBar_laser.setGeometry(QtCore.QRect(240, 20, 181, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_laser.sizePolicy().hasHeightForWidth())
        self.progressBar_laser.setSizePolicy(sizePolicy)
        self.progressBar_laser.setProperty("value", 0)
        self.progressBar_laser.setObjectName("progressBar_laser")
        self.choose_directory_button = QtWidgets.QPushButton(self.tab_acquisition)
        self.choose_directory_button.setGeometry(QtCore.QRect(430, 20, 81, 71))
        self.choose_directory_button.setStyleSheet("qproperty-icon: url(\"img:folder.svg\");")
        self.choose_directory_button.setText("")
        self.choose_directory_button.setIconSize(QtCore.QSize(48, 48))
        self.choose_directory_button.setObjectName("choose_directory_button")
        self.current_directory_label = QtWidgets.QLabel(self.tab_acquisition)
        self.current_directory_label.setGeometry(QtCore.QRect(480, 90, 431, 41))
        self.current_directory_label.setText("")
        self.current_directory_label.setObjectName("current_directory_label")
        self.one_shot_filename_box = QtWidgets.QLineEdit(self.tab_acquisition)
        self.one_shot_filename_box.setGeometry(QtCore.QRect(610, 36, 301, 41))
        self.one_shot_filename_box.setObjectName("one_shot_filename_box")
        self.go_button = QtWidgets.QPushButton(self.tab_acquisition)
        self.go_button.setEnabled(False)
        self.go_button.setGeometry(QtCore.QRect(10, 130, 211, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.go_button.setPalette(palette)
        self.go_button.setStyleSheet("")
        self.go_button.setIconSize(QtCore.QSize(32, 32))
        self.go_button.setObjectName("go_button")
        self.label_27 = QtWidgets.QLabel(self.tab_acquisition)
        self.label_27.setGeometry(QtCore.QRect(460, 150, 71, 31))
        self.label_27.setObjectName("label_27")
        self.profile_steps_combobox = QtWidgets.QComboBox(self.tab_acquisition)
        self.profile_steps_combobox.setGeometry(QtCore.QRect(520, 146, 81, 41))
        self.profile_steps_combobox.setObjectName("profile_steps_combobox")
        self.label_28 = QtWidgets.QLabel(self.tab_acquisition)
        self.label_28.setGeometry(QtCore.QRect(520, 40, 101, 31))
        self.label_28.setObjectName("label_28")
        self.profile_go_button = QtWidgets.QPushButton(self.tab_acquisition)
        self.profile_go_button.setEnabled(False)
        self.profile_go_button.setGeometry(QtCore.QRect(240, 130, 211, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.profile_go_button.setPalette(palette)
        self.profile_go_button.setStyleSheet("")
        self.profile_go_button.setIconSize(QtCore.QSize(32, 32))
        self.profile_go_button.setObjectName("profile_go_button")
        self.shots_delay_combobox = QtWidgets.QComboBox(self.tab_acquisition)
        self.shots_delay_combobox.setGeometry(QtCore.QRect(830, 146, 81, 41))
        self.shots_delay_combobox.setObjectName("shots_delay_combobox")
        self.label_29 = QtWidgets.QLabel(self.tab_acquisition)
        self.label_29.setGeometry(QtCore.QRect(610, 150, 221, 31))
        self.label_29.setObjectName("label_29")
        self.one_shot_detect_btn = QtWidgets.QPushButton(self.tab_acquisition)
        self.one_shot_detect_btn.setGeometry(QtCore.QRect(650, 200, 151, 41))
        self.one_shot_detect_btn.setObjectName("one_shot_detect_btn")
        self.tabWidget.addTab(self.tab_acquisition, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.trigger_delay_combobox = QtWidgets.QComboBox(self.tab_2)
        self.trigger_delay_combobox.setGeometry(QtCore.QRect(250, 90, 81, 31))
        self.trigger_delay_combobox.setObjectName("trigger_delay_combobox")
        self.label_trigger = QtWidgets.QLabel(self.tab_2)
        self.label_trigger.setGeometry(QtCore.QRect(20, 80, 191, 41))
        self.label_trigger.setObjectName("label_trigger")
        self.integration_time_combobox = QtWidgets.QComboBox(self.tab_2)
        self.integration_time_combobox.setGeometry(QtCore.QRect(300, 40, 81, 31))
        self.integration_time_combobox.setObjectName("integration_time_combobox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 130, 391, 271))
        self.groupBox_3.setObjectName("groupBox_3")
        self.prominence_spinbox = QtWidgets.QSpinBox(self.groupBox_3)
        self.prominence_spinbox.setGeometry(QtCore.QRect(220, 110, 91, 31))
        self.prominence_spinbox.setMaximum(5000)
        self.prominence_spinbox.setProperty("value", 500)
        self.prominence_spinbox.setObjectName("prominence_spinbox")
        self.distance_spinbox = QtWidgets.QSpinBox(self.groupBox_3)
        self.distance_spinbox.setGeometry(QtCore.QRect(220, 150, 71, 31))
        self.distance_spinbox.setMaximum(100)
        self.distance_spinbox.setProperty("value", 3)
        self.distance_spinbox.setObjectName("distance_spinbox")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(50, 100, 161, 31))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(50, 150, 91, 20))
        self.label_23.setObjectName("label_23")
        self.show_grid_option = QtWidgets.QCheckBox(self.groupBox_3)
        self.show_grid_option.setGeometry(QtCore.QRect(20, 190, 191, 41))
        self.show_grid_option.setChecked(True)
        self.show_grid_option.setObjectName("show_grid_option")
        self.label_integration = QtWidgets.QLabel(self.tab_2)
        self.label_integration.setGeometry(QtCore.QRect(20, 30, 171, 41))
        self.label_integration.setObjectName("label_integration")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_spectrometers = QtWidgets.QWidget()
        self.tab_spectrometers.setObjectName("tab_spectrometers")
        self.spectrometer_tab_widget = QtWidgets.QWidget(self.tab_spectrometers)
        self.spectrometer_tab_widget.setGeometry(QtCore.QRect(10, 10, 911, 891))
        self.spectrometer_tab_widget.setObjectName("spectrometer_tab_widget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.spectrometer_tab_widget)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.spectrometer_info_label = QtWidgets.QLabel(self.spectrometer_tab_widget)
        self.spectrometer_info_label.setWordWrap(True)
        self.spectrometer_info_label.setObjectName("spectrometer_info_label")
        self.verticalLayout_12.addWidget(self.spectrometer_info_label)
        self.detect_spectrometers_button = QtWidgets.QPushButton(self.spectrometer_tab_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detect_spectrometers_button.sizePolicy().hasHeightForWidth())
        self.detect_spectrometers_button.setSizePolicy(sizePolicy)
        self.detect_spectrometers_button.setObjectName("detect_spectrometers_button")
        self.verticalLayout_12.addWidget(self.detect_spectrometers_button, 0, QtCore.Qt.AlignLeft)
        self.spectrometer_list_widget = QtWidgets.QListWidget(self.spectrometer_tab_widget)
        self.spectrometer_list_widget.setObjectName("spectrometer_list_widget")
        self.spectrometer_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.verticalLayout_12.addWidget(self.spectrometer_list_widget)
        self.tabWidget.addTab(self.tab_spectrometers, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(1210, 20, 681, 951))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 651, 461))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.display_micro = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.display_micro.setContentsMargins(0, 0, 0, 0)
        self.display_micro.setObjectName("display_micro")
        self.save_micro_capture = QtWidgets.QPushButton(self.tab)
        self.save_micro_capture.setGeometry(QtCore.QRect(20, 500, 241, 51))
        self.save_micro_capture.setObjectName("save_micro_capture")
        self.micro_light_checkbox = QtWidgets.QCheckBox(self.tab)
        self.micro_light_checkbox.setGeometry(QtCore.QRect(300, 510, 81, 31))
        self.micro_light_checkbox.setChecked(False)
        self.micro_light_checkbox.setObjectName("micro_light_checkbox")
        self.console_box = QtWidgets.QTextEdit(self.tab)
        self.console_box.setGeometry(QtCore.QRect(10, 680, 651, 211))
        self.console_box.setObjectName("console_box")
        self.tabWidget_2.addTab(self.tab, "")
        self.manual_controls = QtWidgets.QGroupBox(self.centralwidget)
        self.manual_controls.setGeometry(QtCore.QRect(960, 50, 241, 511))
        self.manual_controls.setObjectName("manual_controls")
        self.north_button = QtWidgets.QPushButton(self.manual_controls)
        self.north_button.setEnabled(False)
        self.north_button.setGeometry(QtCore.QRect(70, 40, 41, 41))
        self.north_button.setStyleSheet("qproperty-icon: url(\"img:arrow-up.svg\");")
        self.north_button.setText("")
        self.north_button.setIconSize(QtCore.QSize(48, 48))
        self.north_button.setFlat(True)
        self.north_button.setObjectName("north_button")
        self.up_button = QtWidgets.QPushButton(self.manual_controls)
        self.up_button.setEnabled(False)
        self.up_button.setGeometry(QtCore.QRect(180, 40, 41, 41))
        self.up_button.setStyleSheet("qproperty-icon: url(\"img:chevrons-up.svg\");")
        self.up_button.setText("")
        self.up_button.setIconSize(QtCore.QSize(48, 48))
        self.up_button.setFlat(True)
        self.up_button.setObjectName("up_button")
        self.south_button = QtWidgets.QPushButton(self.manual_controls)
        self.south_button.setEnabled(False)
        self.south_button.setGeometry(QtCore.QRect(70, 140, 41, 41))
        self.south_button.setStyleSheet("qproperty-icon: url(\"img:arrow-down.svg\");")
        self.south_button.setText("")
        self.south_button.setIconSize(QtCore.QSize(48, 48))
        self.south_button.setFlat(True)
        self.south_button.setObjectName("south_button")
        self.down_button = QtWidgets.QPushButton(self.manual_controls)
        self.down_button.setEnabled(False)
        self.down_button.setGeometry(QtCore.QRect(180, 140, 41, 41))
        self.down_button.setStyleSheet("qproperty-icon: url(\"img:chevrons-down.svg\");")
        self.down_button.setText("")
        self.down_button.setIconSize(QtCore.QSize(48, 48))
        self.down_button.setFlat(True)
        self.down_button.setObjectName("down_button")
        self.west_button = QtWidgets.QPushButton(self.manual_controls)
        self.west_button.setEnabled(False)
        self.west_button.setGeometry(QtCore.QRect(20, 90, 41, 41))
        self.west_button.setStyleSheet("qproperty-icon: url(\"img:arrow-left.svg\");")
        self.west_button.setText("")
        self.west_button.setIconSize(QtCore.QSize(48, 48))
        self.west_button.setFlat(True)
        self.west_button.setObjectName("west_button")
        self.east_button = QtWidgets.QPushButton(self.manual_controls)
        self.east_button.setEnabled(False)
        self.east_button.setGeometry(QtCore.QRect(120, 90, 41, 41))
        self.east_button.setStyleSheet("qproperty-icon: url(\"img:arrow-right.svg\");")
        self.east_button.setText("")
        self.east_button.setIconSize(QtCore.QSize(48, 48))
        self.east_button.setFlat(True)
        self.east_button.setObjectName("east_button")
        self.stop_button = QtWidgets.QPushButton(self.manual_controls)
        self.stop_button.setEnabled(False)
        self.stop_button.setGeometry(QtCore.QRect(10, 360, 221, 141))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.stop_button.setPalette(palette)
        self.stop_button.setStyleSheet("background-color: #DCDCDC;\n"
"qproperty-icon: url(\"img:x-octagon.svg\");")
        self.stop_button.setIconSize(QtCore.QSize(48, 48))
        self.stop_button.setFlat(False)
        self.stop_button.setObjectName("stop_button")
        self.label_6 = QtWidgets.QLabel(self.manual_controls)
        self.label_6.setGeometry(QtCore.QRect(75, 94, 41, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_6.setPalette(palette)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.manual_controls)
        self.label_7.setGeometry(QtCore.QRect(190, 94, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_7.setPalette(palette)
        self.label_7.setObjectName("label_7")
        self.steps_z_spinbox = QtWidgets.QSpinBox(self.manual_controls)
        self.steps_z_spinbox.setGeometry(QtCore.QRect(250, 310, 101, 31))
        self.steps_z_spinbox.setMinimum(1)
        self.steps_z_spinbox.setMaximum(100000)
        self.steps_z_spinbox.setSingleStep(25)
        self.steps_z_spinbox.setObjectName("steps_z_spinbox")
        self.label_5 = QtWidgets.QLabel(self.manual_controls)
        self.label_5.setGeometry(QtCore.QRect(10, 310, 111, 31))
        self.label_5.setObjectName("label_5")
        self.steps_xy_spinbox = QtWidgets.QSpinBox(self.manual_controls)
        self.steps_xy_spinbox.setGeometry(QtCore.QRect(300, 270, 101, 31))
        self.steps_xy_spinbox.setMinimum(1)
        self.steps_xy_spinbox.setMaximum(100000)
        self.steps_xy_spinbox.setSingleStep(25)
        self.steps_xy_spinbox.setObjectName("steps_xy_spinbox")
        self.label_4 = QtWidgets.QLabel(self.manual_controls)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 131, 31))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.exitAction = QtWidgets.QAction(MainWindow)
        self.exitAction.setObjectName("exitAction")
        self.actionLoad_points = QtWidgets.QAction(MainWindow)
        self.actionLoad_points.setCheckable(False)
        self.actionLoad_points.setObjectName("actionLoad_points")
        self.actionManual_pdf = QtWidgets.QAction(MainWindow)
        self.actionManual_pdf.setCheckable(False)
        self.actionManual_pdf.setObjectName("actionManual_pdf")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionTable_settings = QtWidgets.QAction(MainWindow)
        self.actionTable_settings.setObjectName("actionTable_settings")
        self.actionIO_Matchbox = QtWidgets.QAction(MainWindow)
        self.actionIO_Matchbox.setCheckable(True)
        self.actionIO_Matchbox.setChecked(True)
        self.actionIO_Matchbox.setObjectName("actionIO_Matchbox")
        self.actionSPI_G4 = QtWidgets.QAction(MainWindow)
        self.actionSPI_G4.setCheckable(True)
        self.actionSPI_G4.setObjectName("actionSPI_G4")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.exitAction.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.external_laser_checkbox.setToolTip(_translate("MainWindow", "Use external laser (no LAN). Spectrometer waits for external trigger."))
        self.external_laser_checkbox.setText(_translate("MainWindow", "External laser"))
        self.laser_stop_button.setText(_translate("MainWindow", "Stop"))
        self.Connect_laser_button.setText(_translate("MainWindow", "Connect to Laser"))
        self.one_shot_filename_box.setText(_translate("MainWindow", "test"))
        self.go_button.setText(_translate("MainWindow", "ONE SHOT"))
        self.label_27.setText(_translate("MainWindow", "shots:"))
        self.label_28.setText(_translate("MainWindow", "filename:"))
        self.profile_go_button.setText(_translate("MainWindow", "MULTI SHOTS"))
        self.label_29.setText(_translate("MainWindow", "delay between shots (s):"))
        self.one_shot_detect_btn.setText(_translate("MainWindow", "Detect peaks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_acquisition), _translate("MainWindow", "One shot"))
        self.label_trigger.setText(_translate("MainWindow", "Trigger delay (ns):"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Peaks"))
        self.label_22.setText(_translate("MainWindow", "Prominence:"))
        self.label_23.setText(_translate("MainWindow", "Distance:"))
        self.show_grid_option.setText(_translate("MainWindow", "show grid"))
        self.label_integration.setText(_translate("MainWindow", "Integration (µs):"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings"))
        self.spectrometer_info_label.setText(_translate("MainWindow", "Detected spectrometers are listed below. Select which devices participate in One Shot and Multi Shot acquisitions."))
        self.detect_spectrometers_button.setText(_translate("MainWindow", "Reset / Detect Spectrometers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_spectrometers), _translate("MainWindow", "Spectrometers"))
        self.save_micro_capture.setText(_translate("MainWindow", "Save micro capture"))
        self.micro_light_checkbox.setText(_translate("MainWindow", "Light"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Micro View"))
        self.manual_controls.setTitle(_translate("MainWindow", "Table Manual Control"))
        self.stop_button.setText(_translate("MainWindow", "STOP"))
        self.label_6.setText(_translate("MainWindow", "XY"))
        self.label_7.setText(_translate("MainWindow", "Z"))
        self.label_5.setText(_translate("MainWindow", "Step Z (µm)"))
        self.label_4.setText(_translate("MainWindow", "Step XY (µm)"))
        self.exitAction.setText(_translate("MainWindow", "Exit"))
        self.exitAction.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionLoad_points.setText(_translate("MainWindow", "Load points"))
        self.actionManual_pdf.setText(_translate("MainWindow", "Manual (pdf)"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionTable_settings.setText(_translate("MainWindow", "Table settings"))
        self.actionIO_Matchbox.setText(_translate("MainWindow", "IO Matchbox"))
        self.actionSPI_G4.setText(_translate("MainWindow", "SPI G4"))
